export const ADMIN_BLOGPOSTS_REQUEST = "ADMIN_BLOGPOSTS_REQUEST";
export const ADMIN_BLOGPOSTS_SUCCESS = "ADMIN_BLOGPOSTS_SUCCESS";
export const ADMIN_BLOGPOSTS_FAIL = "ADMIN_BLOGPOSTS_FAIL";

export const ALL_BLOGPOSTS_REQUEST = "ALL_BLOGPOSTS_REQUEST";
export const ALL_BLOGPOSTS_SUCCESS = "ALL_BLOGPOSTS_SUCCESS";
export const ALL_BLOGPOSTS_FAIL = "ALL_BLOGPOSTS_FAIL";

export const NEW_BLOGPOST_REQUEST = "NEW_BLOGPOST_REQUEST";
export const NEW_BLOGPOST_SUCCESS = "NEW_BLOGPOST_SUCCESS";
export const NEW_BLOGPOST_RESET = "NEW_BLOGPOST_RESET";
export const NEW_BLOGPOST_FAIL = "NEW_BLOGPOST_FAIL";

export const DELETE_BLOGPOST_REQUEST = "DELETE_BLOGPOST_REQUEST";
export const DELETE_BLOGPOST_SUCCESS = "DELETE_BLOGPOST_SUCCESS";
export const DELETE_BLOGPOST_RESET = "DELETE_BLOGPOST_RESET";
export const DELETE_BLOGPOST_FAIL = "DELETE_BLOGPOST_FAIL";

export const UPDATE_BLOGPOST_REQUEST = "UPDATE_BLOGPOST_REQUEST";
export const UPDATE_BLOGPOST_SUCCESS = "UPDATE_BLOGPOST_SUCCESS";
export const UPDATE_BLOGPOST_RESET = "UPDATE_BLOGPOST_RESET";
export const UPDATE_BLOGPOST_FAIL = "UPDATE_BLOGPOST_FAIL";

export const BLOGPOST_DETAILS_REQUEST = "BLOGPOST_DETAILS_REQUEST";
export const BLOGPOST_DETAILS_SUCCESS = "BLOGPOST_DETAILS_SUCCESS";
export const BLOGPOST_DETAILS_FAIL = "BLOGPOST_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
