export const ADMIN_CANDIDATES_REQUEST = "ADMIN_CANDIDATES_REQUEST";
export const ADMIN_CANDIDATES_SUCCESS = "ADMIN_CANDIDATES_SUCCESS";
export const ADMIN_CANDIDATES_FAIL = "ADMIN_CANDIDATES_FAIL";

export const ALL_CANDIDATES_REQUEST = "ALL_CANDIDATES_REQUEST";
export const ALL_CANDIDATES_SUCCESS = "ALL_CANDIDATES_SUCCESS";
export const ALL_CANDIDATES_FAIL = "ALL_CANDIDATES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
