export const ALL_POSTJOB_REQUEST = "ALL_POSTJOB_REQUEST";
export const ALL_POSTJOB_SUCCESS = "ALL_POSTJOB_SUCCESS";
export const ALL_POSTJOB_FAIL = "ALL_POSTJOB_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
